apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://grafana.github.io/helm-charts"
    chart: grafana
    targetRevision: "8.6.0"    # ajustar se quiser outra versão
    helm:
      values: |
        adminUser: admin
        adminPassword: admin
        service:
          type: LoadBalancer
# To use LoadBalancer instead (MetalLB):
#        service:
#          type: LoadBalancer
#          annotations: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
